[package]
name = "bevy-hikari"
version = "0.2.0"
edition = "2021"
authors = ["Zhenyuan Zhang <cryscan@umich.edu>"]
license = "MIT OR Apache-2.0"
description = "Voxel Cone Tracing Global Illumination for the Bevy Engine."
homepage = "https://github.com/cryscan/bevy-hikari"
repository = "https://github.com/cryscan/bevy-hikari"
keywords = ["gamedev", "graphics", "bevy", "3d"]
categories = ["game-engines", "rendering"]
exclude = ["assets"]

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_pbr",
] }
bytemuck = "1.9"
itertools = "0.10"
bvh = "0.6"

[dev-dependencies]
bevy = { version = "0.8", default-features = true, features = [
    "bevy_gltf",
    "jpeg",
    "png",
    "x11",
] }
